define([],
() => {
    const SET_CHECKLIST_ITEMS = 'SET_CHECKLIST_ITEMS';
    const CREATE_CHECKLIST_ITEM = 'CREATE_CHECKLIST_ITEM';
    const UPDATE_CHECKLIST_ITEM = 'UPDATE_CHECKLIST_ITEM';
    const DELETE_CHECKLIST_ITEM = 'DELETE_CHECKLIST_ITEM';

    return {
        SET_CHECKLIST_ITEMS,
        CREATE_CHECKLIST_ITEM,
        UPDATE_CHECKLIST_ITEM,
        DELETE_CHECKLIST_ITEM
    };
});